-- Schema SQL (MySQL) matching prisma/schema.prisma

CREATE TABLE Usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firebaseUid VARCHAR(191) NOT NULL UNIQUE,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  perfil VARCHAR(50) NOT NULL DEFAULT 'cliente',
  criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cliente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuarioId INT NOT NULL UNIQUE,
  telefone VARCHAR(50),
  endereco VARCHAR(255),
  criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuarioId) REFERENCES Usuario(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Profissional (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuarioId INT NOT NULL UNIQUE,
  especialidade VARCHAR(255),
  telefone VARCHAR(50),
  criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuarioId) REFERENCES Usuario(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Servico (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  preco DOUBLE NOT NULL,
  dururaMin INT NOT NULL,
  profissionalId INT,
  FOREIGN KEY (profissionalId) REFERENCES Profissional(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Agendamento (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clienteId INT NOT NULL,
  servicoId INT NOT NULL,
  profissionalId INT,
  data DATETIME NOT NULL,
  horario VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'agendado',
  criadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (clienteId) REFERENCES Cliente(id) ON DELETE CASCADE,
  FOREIGN KEY (servicoId) REFERENCES Servico(id) ON DELETE CASCADE,
  FOREIGN KEY (profissionalId) REFERENCES Profissional(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
